[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#31333F"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "developer"

[logger]
level = "info"

[server]
headless = true
runOnSave = true
maxUploadSize = 200
# Aumentar timeout para scrapers y descarga de ChromeDriver
maxMessageSize = 50
enableXsrfProtection = false

[browser]
gatherUsageStats = false
